
apiVersion: apps/v1
kind :Deployment
metadata
  name :backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image : 152658500028.dkr.ecr.ap-southeast-2.amazonaws.com/techscrum-ecr-repo:latest
          ports:
            - containerPort: 8000


---
apiVersion: v1
kind :Service
metadata:
  name :backend-cluster-ip-service
spec:
  type :ClusterIP
  selector:
    component: backend
  ports:
    - port: 8000
      targetPort :8000
